CREATE SMALLFILE TABLESPACE IDAMAN_HOLIDAYS
DATAFILE
    'C:\oraclexe\app\oracle\oradata\XE\IDAMAN.dbf' SIZE 100M
NOLOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE IDAMAN_HOLIDAYS LOGGING;

CREATE TABLE HR.IDAMAN_CUSTOMER(
CUST_ID NUMBER(4,2) NOT NULL PRIMARY KEY,
CUST_NAME VARCHAR2(50) NOT NULL,
CUST_ADDRESS VARCHAR2(100) NOT NULL,
CUST_PHONE VARCHAR2(15) NOT NULL,
CUST_DATE_DEP  DATE NOT NULL,
CUST_DATE_RET  DATE NOT NULL,
CUST_PACKAGE VARCHAR2(15) NOT NULL
);

INSERT INTO HR.IDAMAN_CUSTOMER
(CUST_ID, CUST_NAME, CUST_ADDRESS, CUST_PHONE, CUST_DATE_DEP, CUST_DATE_RET, CUST_PACKAGE)
VALUES
(1, 'FAIRUS', 'KG. PANDAN, KL', '0126743007', TO_DATE('01/12/2020', 'DD/MM/YYYY'), 
TO_DATE('05/12/2020', 'DD/MM/YYYY'), 'PACKAGE A');

INSERT INTO HR.IDAMAN_CUSTOMER
(CUST_ID, CUST_NAME, CUST_ADDRESS, CUST_PHONE, CUST_DATE_DEP, CUST_DATE_RET, CUST_PACKAGE)
VALUES
(2, 'FARIDAH', 'TAMAN SRI DAMAI, PERAK', '0176024445', TO_DATE('06/12/2020', 'DD/MM/YYYY'), 
TO_DATE('12/12/2020', 'DD/MM/YYYY'), 'PACKAGE B');

INSERT INTO HR.IDAMAN_CUSTOMER
(CUST_ID, CUST_NAME, CUST_ADDRESS, CUST_PHONE, CUST_DATE_DEP, CUST_DATE_RET, CUST_PACKAGE)
VALUES
(3, 'SENAWI', 'JENGKA, PAHANG', '0196783043', TO_DATE('13/12/2020', 'DD/MM/YYYY'), 
TO_DATE('15/12/2020', 'DD/MM/YYYY'), 'PACKAGE A');

CREATE USER FAUZIAH
IDENTIFIED BY Hafsha99
DEFAULT TABLESPACE IDAMAN_HOLIDAYS
TEMPORARY TABLESPACE TEMP;

CREATE USER NAZIRAH
IDENTIFIED BY Hafsha99
DEFAULT TABLESPACE IDAMAN_HOLIDAYS
TEMPORARY TABLESPACE TEMP;

CREATE USER RIZIAUDDIN
IDENTIFIED BY Hafsha99
DEFAULT TABLESPACE IDAMAN_HOLIDAYS
TEMPORARY TABLESPACE TEMP;

CREATE ROLE MANAGER;
GRANT CREATE TABLE TO MANAGER;
GRANT CREATE SESSION TO MANAGER;
GRANT SELECT ON HR.IDAMAN_CUSTOMER TO MANAGER;
GRANT INSERT ON HR.IDAMAN_CUSTOMER TO MANAGER;
GRANT UPDATE ON HR.IDAMAN_CUSTOMER TO MANAGER;
GRANT DELETE ON HR.IDAMAN_CUSTOMER TO MANAGER;

GRANT MANAGER TO FAUZIAH;

CREATE ROLE RECEPTIONIST;
GRANT CREATE SESSION TO RECEPTIONIST;
GRANT SELECT ON HR.IDAMAN_CUSTOMER TO RECEPTIONIST;
GRANT INSERT ON HR.IDAMAN_CUSTOMER TO RECEPTIONIST;
GRANT UPDATE ON HR.IDAMAN_CUSTOMER TO RECEPTIONIST;
GRANT DELETE ON HR.IDAMAN_CUSTOMER TO RECEPTIONIST;

GRANT RECEPTIONIST TO NAZIRAH;

CREATE ROLE CEO;
GRANT SELECT ON HR.IDAMAN_CUSTOMER TO CEO;
GRANT UPDATE ON HR.IDAMAN_CUSTOMER TO CEO;

GRANT CEO TO RIZIAUDDIN;

ALTER TABLE HR.IDAMAN_CUSTOMER 
ENABLE ROW MOVEMENT;




