CREATE SMALLFILE TABLESPACE RESTAURANT
DATAFILE
    'C:\oraclexe\app\oracle\oradata\XE\AMIGO.dbf' SIZE 300K
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLE AMIGO_EMPLOYEE
(
Emp_ID number(4,2) NOT NULL,
Emp_NAME varchar2(30) NOT NULL,
POSITION_ID varchar2(30)
);

ALTER TABLE AMIGO_EMPLOYEE
MODIFY Emp_ID number(4,2) PRIMARY KEY;

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('01','SARAH','1');

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('02','MICHEAL','2');

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('03','ANGELO','3');

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('04','HUDSON','3');

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('05','TIM','3');

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('06','RUBY','4');

INSERT INTO AMIGO_EMPLOYEE
(Emp_ID, Emp_NAME, POSITION_ID)
VALUES
('07','MAX','4');









