CREATE TABLE HR.AMIGO_EMPLOYEE
(
EMP_ID NUMBER(4,2) NOT NULL PRIMARY KEY,
EMP_NAME VARCHAR2(30) NOT NULL,
POSITION_ID VARCHAR2(30)
);

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(01, 'SARAH', '1');

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(02, 'MICHEAL', '2');

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(03, 'ANGELO', '3');

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(04, 'HUDSON', '3');

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(05, 'TIM', '3');

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(06, 'RUBY', '4');

INSERT INTO HR.AMIGO_EMPLOYEE
(EMP_ID, EMP_NAME, POSITION_ID)
VALUES 
(07, 'MAX', '4');

CREATE INDEX AMIGO_INDEX_POSITION 
ON HR.AMIGO_EMPLOYEE(POSITION_ID)
TABLESPACE RESTAURANT;

CREATE VIEW HR.VIEW_MANAGER
AS
SELECT * FROM HR.AMIGO_EMPLOYEE
WHERE POSITION_ID = '2';

CREATE VIEW HR.VIEW_CASHIER
AS
SELECT * FROM HR.AMIGO_EMPLOYEE
WHERE POSITION_ID = '3';

CREATE USER MICHEAL
IDENTIFIED BY Hafsha99
DEFAULT TABLESPACE RESTAURANT
TEMPORARY TABLESPACE TEMP;

CREATE ROLE MANAGER;

GRANT CREATE TABLE TO MANAGER;

GRANT CREATE SESSION TO MANAGER;

GRANT SELECT ON HR.AMIGO_EMPLOYEE TO MANAGER;

GRANT INSERT ON HR.AMIGO_EMPLOYEE TO MANAGER;

CREATE ROLE CASHIER;

GRANT CREATE TABLE TO CASHIER;

GRANT CREATE SESSION TO CASHIER;

GRANT SELECT ON HR.AMIGO_EMPLOYEE TO CASHIER;

GRANT MANAGER TO MICHEAL;


